services:
  - type: web
    name: khatwa-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: node dist/src/main.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_HOST
        value: ep-wispy-cloud-aq1uqcdz-pooler.c-8.us-east-1.aws.neon.tech
      - key: DATABASE_PORT
        value: "5432"
      - key: DATABASE_USERNAME
        value: neondb_owner
      - key: DATABASE_PASSWORD
        value: npg_9fFmVjSInK2P
      - key: DATABASE_NAME
        value: neondb
      - key: JWT_SECRET
        value: 4068be254d9ff012f05bf23ac2f37a30abf1c79006f247b542de8e6195ace3464cd76c51f6d04f5ac32995bda8b44843
      - key: FRONTEND_ORIGIN
        value: https://khatwa.vercel.app
      - key: PGSSLMODE
        value: require
